# Generated by Django 4.0.2 on 2022-03-06 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(max_length=20)),
                ('orderdetail', models.CharField(max_length=20)),
                ('total', models.CharField(max_length=100)),
                ('orderdate', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderticket.customer')),
            ],
        ),
    ]
