# Generated by Django 4.0.2 on 2022-03-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderticket', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderdetail',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='race',
            field=models.CharField(max_length=500),
        ),
    ]
