# Generated by Django 4.0.2 on 2022-03-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderticket', '0003_alter_order_orderdetail_alter_order_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordertag',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
