# Generated by Django 3.2.12 on 2022-04-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderticket', '0004_order_ordertag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderdetail',
            field=models.CharField(max_length=2000),
        ),
    ]
