# Generated by Django 4.0.2 on 2022-09-08 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderticket', '0005_alter_order_orderdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='order',
        ),
    ]
